# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: futbol_mensajes.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'futbol_mensajes.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x66utbol_mensajes.proto\"\x92\x01\n\x11VariableAleatoria\x12\x0e\n\x06nombre\x18\x01 \x01(\t\x12#\n\x0b\x65xponencial\x18\x02 \x01(\x0b\x32\x0c.ExponencialH\x00\x12\x19\n\x06normal\x18\x03 \x01(\x0b\x32\x07.NormalH\x00\x12\x1d\n\x08uniforme\x18\x04 \x01(\x0b\x32\t.UniformeH\x00\x42\x0e\n\x0c\x64istribucion\"\x1d\n\x0b\x45xponencial\x12\x0e\n\x06lambda\x18\x01 \x01(\x01\"#\n\x06Normal\x12\n\n\x02mu\x18\x01 \x01(\x01\x12\r\n\x05sigma\x18\x02 \x01(\x01\"$\n\x08Uniforme\x12\x0b\n\x03min\x18\x01 \x01(\x01\x12\x0b\n\x03max\x18\x02 \x01(\x01\"d\n\x0cModeloFutbol\x12\x11\n\tid_modelo\x18\x01 \x01(\t\x12%\n\tvariables\x18\x02 \x03(\x0b\x32\x12.VariableAleatoria\x12\x1a\n\x12\x66ormula_evaluacion\x18\x03 \x01(\t\"\xa4\x01\n\x10\x45scenarioPartido\x12\x14\n\x0cid_escenario\x18\x01 \x01(\t\x12\x13\n\x0bt_gol_local\x18\x02 \x01(\x01\x12\x17\n\x0ft_gol_visitante\x18\x03 \x01(\x01\x12\x19\n\x11rendimiento_local\x18\x04 \x01(\x01\x12\x1d\n\x15rendimiento_visitante\x18\x05 \x01(\x01\x12\x12\n\nfactor_var\x18\x06 \x01(\x01\"j\n\x10ResultadoPartido\x12\x14\n\x0cid_escenario\x18\x01 \x01(\t\x12\x12\n\ngana_local\x18\x02 \x01(\x08\x12\x13\n\x0bgoles_local\x18\x03 \x01(\x05\x12\x17\n\x0fgoles_visitante\x18\x04 \x01(\x05\"\x8b\x01\n\x11\x45ventoEstadistica\x12\x0e\n\x06origen\x18\x01 \x01(\t\x12\x18\n\x10tasa_por_segundo\x18\x02 \x01(\x01\x12-\n%probabilidad_victoria_local_acumulada\x18\x03 \x01(\x01\x12\x1d\n\x15\x65scenarios_procesados\x18\x04 \x01(\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'futbol_mensajes_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VARIABLEALEATORIA']._serialized_start=26
  _globals['_VARIABLEALEATORIA']._serialized_end=172
  _globals['_EXPONENCIAL']._serialized_start=174
  _globals['_EXPONENCIAL']._serialized_end=203
  _globals['_NORMAL']._serialized_start=205
  _globals['_NORMAL']._serialized_end=240
  _globals['_UNIFORME']._serialized_start=242
  _globals['_UNIFORME']._serialized_end=278
  _globals['_MODELOFUTBOL']._serialized_start=280
  _globals['_MODELOFUTBOL']._serialized_end=380
  _globals['_ESCENARIOPARTIDO']._serialized_start=383
  _globals['_ESCENARIOPARTIDO']._serialized_end=547
  _globals['_RESULTADOPARTIDO']._serialized_start=549
  _globals['_RESULTADOPARTIDO']._serialized_end=655
  _globals['_EVENTOESTADISTICA']._serialized_start=658
  _globals['_EVENTOESTADISTICA']._serialized_end=797
# @@protoc_insertion_point(module_scope)
